services:
  - type: web
    name: infohub-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: WEATHER_API_KEY
        value: 66f70c3969a272ed5f7963f46cb5ebdf

  - type: web
    name: infohub-client
    env: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://infohub-challenge-ev5i.onrender.com
